### ISSUE TITLE
Timecodes for "ML Zoomcamp 4.2 - Accuracy and Dummy Model"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#193]
Youtube video: https://www.youtube.com/watch?v=FW_l7lB0HUI

**Comment by tummala-hareesh** [comment]
00:00 Introduction 
00:15 Accuracy calculation explanation 
01:15 Accuracy on all customers example
03:20 Is the used Churn threshold good? 
03:50 Calculating accuracy for different thresholds
05:01 Line plot of thresholds vs scores
06:15 Logistic Regression optimizes for high score
06:35 Accuracy metric from scikit learn
07:51 Interpreting First and Last thresholds
09:55 Why bother? our model vs dummy model scores
12:10 Issues due to class imbalances in datasets
13:01 What's in the Next Lesson?

@amitfrancis

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
